import React, { useState, useMemo } from 'react';
import { BusinessRecord, MultiPassBlockingResult, ModelWeights } from '../types/entityResolution';
import { runMultiPassUnionBlocking } from '../core/blocking';
import { evaluatePair } from '../core/model';
import { BENCHMARK_DATASET_RECORDS } from '../data/benchmarkDatasets';
import {
  Layers,
  Filter,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Database,
  ArrowRight,
  TrendingDown,
  Sparkles,
  Search,
  Upload,
  RefreshCw
} from 'lucide-react';

interface BatchBlockingViewProps {
  weights: ModelWeights;
  onInspectPair?: (r1: BusinessRecord, r2: BusinessRecord) => void;
}

export const BatchBlockingView: React.FC<BatchBlockingViewProps> = ({ weights, onInspectPair }) => {
  const [records, setRecords] = useState<BusinessRecord[]>(BENCHMARK_DATASET_RECORDS);
  const [decisionFilter, setDecisionFilter] = useState<'ALL' | 'MATCH' | 'POSSIBLE_MATCH' | 'NO_MATCH'>('ALL');
  const [passFilter, setPassFilter] = useState<number | 'ALL'>('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  // Run the Multi-Pass Union Blocking
  const blockingResult: MultiPassBlockingResult = useMemo(() => {
    return runMultiPassUnionBlocking(records);
  }, [records]);

  // Evaluate all candidate pairs generated by the blocking passes
  const evaluatedCandidatePairs = useMemo(() => {
    return blockingResult.candidatePairs.map(cp => {
      const evalResult = evaluatePair(cp.record1, cp.record2, weights);
      return {
        ...cp,
        evalResult
      };
    });
  }, [blockingResult, weights]);

  // Filter pairs
  const filteredPairs = useMemo(() => {
    return evaluatedCandidatePairs.filter(p => {
      if (decisionFilter !== 'ALL' && p.evalResult.match_decision !== decisionFilter) {
        return false;
      }
      if (passFilter !== 'ALL' && !p.matchedPasses.includes(passFilter)) {
        return false;
      }
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const matchesName =
          p.record1.name.toLowerCase().includes(q) ||
          p.record2.name.toLowerCase().includes(q) ||
          p.record1.address.toLowerCase().includes(q) ||
          p.record2.address.toLowerCase().includes(q);
        if (!matchesName) return false;
      }
      return true;
    });
  }, [evaluatedCandidatePairs, decisionFilter, passFilter, searchQuery]);

  return (
    <div className="space-y-6">
      {/* Header and KPI cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-slate-900 rounded-2xl p-5 border border-slate-800">
          <div className="flex items-center justify-between text-xs text-slate-400 mb-1">
            <span>Total Records (N)</span>
            <Database className="w-4 h-4 text-blue-400" />
          </div>
          <div className="text-2xl font-bold font-mono text-white">{records.length}</div>
          <div className="text-[11px] text-slate-500 mt-1">Loaded registry entries</div>
        </div>

        <div className="bg-slate-900 rounded-2xl p-5 border border-slate-800">
          <div className="flex items-center justify-between text-xs text-slate-400 mb-1">
            <span>Cartesian Product O(N²)</span>
            <span className="text-[10px] font-mono text-slate-500">N·(N-1)/2</span>
          </div>
          <div className="text-2xl font-bold font-mono text-slate-400">
            {blockingResult.totalCartesianPairs}
          </div>
          <div className="text-[11px] text-slate-500 mt-1">Brute-force pair comparisons</div>
        </div>

        <div className="bg-slate-900 rounded-2xl p-5 border border-slate-800">
          <div className="flex items-center justify-between text-xs text-slate-400 mb-1">
            <span>Union Candidates</span>
            <Layers className="w-4 h-4 text-indigo-400" />
          </div>
          <div className="text-2xl font-bold font-mono text-indigo-400">
            {blockingResult.totalCandidatePairs}
          </div>
          <div className="text-[11px] text-slate-500 mt-1">Filtered candidate pairs</div>
        </div>

        <div className="bg-slate-900 rounded-2xl p-5 border border-slate-800">
          <div className="flex items-center justify-between text-xs text-slate-400 mb-1">
            <span>Search Space Reduction</span>
            <TrendingDown className="w-4 h-4 text-emerald-400" />
          </div>
          <div className="text-2xl font-bold font-mono text-emerald-400">
            {blockingResult.reductionRatioPercentage}%
          </div>
          <div className="text-[11px] text-slate-500 mt-1">Zero true-match loss guarantee</div>
        </div>
      </div>

      {/* 4-Pass Union Blocking Visualization Cards */}
      <div className="bg-slate-900 rounded-2xl p-5 border border-slate-800">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-2">
            <Layers className="w-5 h-5 text-indigo-400" />
            <h2 className="text-sm font-bold text-slate-100">Multi-Pass Union Blocking Rules (Prompt Specification)</h2>
          </div>
          <span className="text-xs text-slate-400">Union eliminates candidate dropouts across varied representations</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
          {blockingResult.passResults.map(p => {
            const isFilterActive = passFilter === p.passNumber;
            return (
              <button
                key={p.passNumber}
                onClick={() => setPassFilter(isFilterActive ? 'ALL' : p.passNumber)}
                className={`text-left p-4 rounded-xl border transition-all ${
                  isFilterActive
                    ? 'bg-indigo-950/80 border-indigo-500 text-white shadow-md'
                    : 'bg-slate-950/60 border-slate-800 text-slate-300 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-indigo-400">
                    Pass {p.passNumber}
                  </span>
                  <span className="text-[11px] font-mono px-2 py-0.5 rounded-full bg-slate-800 text-slate-300">
                    {p.generatedPairsCount} pairs
                  </span>
                </div>
                <div className="text-xs font-semibold text-slate-100 mb-1">{p.name}</div>
                <p className="text-[11px] text-slate-400 line-clamp-2">{p.description}</p>
                <div className="mt-2 text-[10px] text-slate-500 font-mono">
                  Buckets/Keys: {p.keysCreatedCount}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Candidate Pairs Table & Filter Controls */}
      <div className="bg-slate-900 rounded-2xl border border-slate-800 overflow-hidden shadow-sm">
        <div className="p-4 border-b border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-3">
          {/* Search */}
          <div className="relative flex-1 max-w-sm">
            <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-500" />
            <input
              type="text"
              placeholder="Search candidate business or address..."
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-4 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500"
            />
          </div>

          {/* Decision Filter Pills */}
          <div className="flex items-center space-x-2">
            <span className="text-xs text-slate-400 font-medium">Filter Decision:</span>
            <div className="flex items-center bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
              {(['ALL', 'MATCH', 'POSSIBLE_MATCH', 'NO_MATCH'] as const).map(d => (
                <button
                  key={d}
                  onClick={() => setDecisionFilter(d)}
                  className={`px-2.5 py-1 rounded-lg font-medium transition-all ${
                    decisionFilter === d
                      ? 'bg-indigo-600 text-white'
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {d}
                </button>
              ))}
            </div>

            {passFilter !== 'ALL' && (
              <button
                onClick={() => setPassFilter('ALL')}
                className="text-xs text-indigo-400 hover:text-indigo-300 px-2 py-1 bg-slate-800 rounded-lg"
              >
                Clear Pass Filter (Pass {passFilter})
              </button>
            )}
          </div>
        </div>

        {/* Pairs List */}
        <div className="divide-y divide-slate-800/80 max-h-[500px] overflow-y-auto">
          {filteredPairs.length === 0 ? (
            <div className="p-8 text-center text-slate-500 text-xs">
              No candidate pairs match the current filter criteria.
            </div>
          ) : (
            filteredPairs.map((p, idx) => {
              const res = p.evalResult;
              const isMatch = res.match_decision === 'MATCH';
              const isPossible = res.match_decision === 'POSSIBLE_MATCH';

              return (
                <div
                  key={idx}
                  className="p-4 hover:bg-slate-800/30 transition-all flex flex-col lg:flex-row lg:items-center justify-between gap-4"
                >
                  {/* Records comparison */}
                  <div className="flex-1 space-y-2">
                    {/* Record 1 */}
                    <div className="flex items-start space-x-2 text-xs">
                      <span className="font-mono text-[10px] text-blue-400 bg-blue-500/10 px-1.5 py-0.5 rounded border border-blue-500/20 shrink-0">
                        {p.record1.id}
                      </span>
                      <div>
                        <span className="font-semibold text-slate-100">{p.record1.name}</span>
                        <span className="text-slate-400 ml-2">{p.record1.address}</span>
                      </div>
                    </div>

                    {/* Record 2 */}
                    <div className="flex items-start space-x-2 text-xs">
                      <span className="font-mono text-[10px] text-purple-400 bg-purple-500/10 px-1.5 py-0.5 rounded border border-purple-500/20 shrink-0">
                        {p.record2.id}
                      </span>
                      <div>
                        <span className="font-semibold text-slate-100">{p.record2.name}</span>
                        <span className="text-slate-400 ml-2">{p.record2.address}</span>
                      </div>
                    </div>

                    {/* Audit note */}
                    <div className="text-[11px] text-slate-500 italic pl-1 border-l-2 border-slate-700">
                      "{res.reasoning}"
                    </div>
                  </div>

                  {/* Matched Passes & Decision */}
                  <div className="flex items-center space-x-4 shrink-0">
                    {/* Matched passes tags */}
                    <div className="flex flex-col items-end">
                      <span className="text-[10px] text-slate-500 mb-1">Triggered Passes</span>
                      <div className="flex items-center space-x-1">
                        {p.matchedPasses.map(passNum => (
                          <span
                            key={passNum}
                            className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-slate-800 text-indigo-300 border border-slate-700"
                            title={`Captured by Pass ${passNum}`}
                          >
                            P{passNum}
                          </span>
                        ))}
                      </div>
                    </div>

                    {/* Decision & Score */}
                    <div className="text-right min-w-[130px]">
                      <div className="flex items-center justify-end space-x-1.5">
                        {isMatch ? (
                          <span className="inline-flex items-center text-xs font-bold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-md border border-emerald-500/20">
                            MATCH
                          </span>
                        ) : isPossible ? (
                          <span className="inline-flex items-center text-xs font-bold text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded-md border border-amber-500/20">
                            POSSIBLE
                          </span>
                        ) : (
                          <span className="inline-flex items-center text-xs font-bold text-rose-400 bg-rose-500/10 px-2 py-0.5 rounded-md border border-rose-500/20">
                            NO_MATCH
                          </span>
                        )}
                        <span className="font-mono font-bold text-sm text-slate-200">
                          {(res.confidence_score * 100).toFixed(0)}%
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>

        <div className="p-3 bg-slate-950 text-xs text-slate-500 border-t border-slate-800 flex items-center justify-between">
          <span>Showing {filteredPairs.length} of {evaluatedCandidatePairs.length} candidate pairs</span>
          <span className="text-[11px]">Union Blocking guarantees zero true match omission</span>
        </div>
      </div>
    </div>
  );
};
